# Generated by Django 5.0.1 on 2024-02-02 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contactus_app', '0002_messege'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Messege',
            new_name='Message',
        ),
    ]
